### ISSUE TITLE
Crystal 0.35

### ISSUE THREAD

**Issue by waghanza** [ZaWertun/fedora-copr-crystal#1]
Hi @ZaWertun,

`crystal` **0.35** is out
https://crystal-lang.org/2020/06/09/crystal-0.35.0-released.html

Do you plan to update this `copr` ?

Regards,

**Comment by ZaWertun** [comment]
https://copr.fedorainfracloud.org/coprs/zawertun/crystal/build/1436948/

**Comment by ZaWertun** [comment]
6ce82e76da1d1d52c81b5b13416f0fefde97f94b
